---
namespace: "simeononsecurity"
name: "windows_update"
description: "Role to automate Windows security patching."
readme: README.md
version: 1.0.2
homepage: "https://simeononsecurity.com/guides/automate-windows-patching-and-updates-with-ansible/"
issues: "https://github.com/simeononsecurity/ansible_windows_update/issues"
repository: "https://github.com/simeononsecurity/ansible_windows_update"
authors:
  - "SimeonOnSecurity (https://simeononsecurity.com)"
license_file: LICENSE
tags:
- role
- windows
build_ignore:
- .github
- .gitattributes
- .gitignore
- .vscode
